// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.GetCSharpDiagnosticAnalyzer~Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.VerifyCSharpDiagnostic(System.String,TestHelper.DiagnosticResult[])")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.VerifyDiagnosticResults(System.Collections.Generic.IEnumerable{Microsoft.CodeAnalysis.Diagnostic},Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer,TestHelper.DiagnosticResult[])")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.GetDocuments(System.String[],System.String)~Microsoft.CodeAnalysis.Document[]")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.GetSortedDiagnostics(System.String[],System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer)~Microsoft.CodeAnalysis.Diagnostic[]")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.FormatDiagnostics(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer,Microsoft.CodeAnalysis.Diagnostic[])~System.String")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.CreateProject(System.String[],System.String)~Microsoft.CodeAnalysis.Project")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.CreateDocument(System.String,System.String)~Microsoft.CodeAnalysis.Document")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.GetSortedDiagnosticsFromDocuments(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer,Microsoft.CodeAnalysis.Document[])~Microsoft.CodeAnalysis.Diagnostic[]")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static elements should appear before instance elements", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~M:TestHelper.DiagnosticVerifier.VerifyDiagnosticResults(System.Collections.Generic.IEnumerable{Microsoft.CodeAnalysis.Diagnostic},Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer,TestHelper.DiagnosticResult[])")]
[assembly: SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "It's provided by VS2019 template and not important. Most likely it will be rewritten completely.", Scope = "member", Target = "~P:TestHelper.DiagnosticResult.Locations")]
